config/routes.rb
NYCustomHydroponics::Application.routes.draw do

  root :to => "pages#home"
  match '/home', :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/videos', :to => 'pages#videos'
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def videos_array
    @vid_title_array = ["First Video: week 2","Second Video: week 3","Third Video: week 4","Fourth Video: Week 5","Fifth Video: Week 6","Sixth Video: week 7","Seventh Video: Week 8","Eighth Video: Week 9","Ninth Video: Week 10"]

    @vid_src_array = ["https://www.youtube.com/embed/El2Jk4VwOpg?feature=player_detailpage","https://www.youtube.com/embed/Fd8KiWwwLb0?feature=player_detailpage","https://www.youtube.com/embed/wg3D1Bomjo4?feature=player_detailpage","https://www.youtube.com/embed/T-sxjN6DyEI?feature=player_detailpage","https://www.youtube.com/embed/3vNG7BiBCmA?feature=player_detailpage","https://www.youtube.com/embed/ijlnYZIwELM?feature=player_detailpage","https://www.youtube.com/embed/2Dtjmk9PvFs?feature=player_detailpage","https://www.youtube.com/embed/iDRdKnBKeJ8?feature=player_detailpage","https://www.youtube.com/embed/zrZPWK5Luws?feature=player_detailpage"]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title ="Home"
    videos_array
  end

  def contact
    @title ="Contact"
  end

  def about
    @title ="About"
  end
  
  def help
    @title ="Help"
  end

  def videos
    @title ="Videos"
    videos_array

    #@vid_title_array = ["First Video: week 2","Second Video: week 3","Third Video: week 4","Fourth Video: Week 5","Fifth Video: Week 6","Sixth Video: week 7","Seventh Video: Week 8","Eighth Video: Week 9","Ninth Video: Week 10"]

    #@vid_src_array = ["https://www.youtube.com/embed/El2Jk4VwOpg?feature=player_detailpage","https://www.youtube.com/embed/Fd8KiWwwLb0?feature=player_detailpage","https://www.youtube.com/embed/wg3D1Bomjo4?feature=player_detailpage","https://www.youtube.com/embed/T-sxjN6DyEI?feature=player_detailpage","https://www.youtube.com/embed/3vNG7BiBCmA?feature=player_detailpage","https://www.youtube.com/embed/ijlnYZIwELM?feature=player_detailpage","https://www.youtube.com/embed/2Dtjmk9PvFs?feature=player_detailpage","https://www.youtube.com/embed/iDRdKnBKeJ8?feature=player_detailpage","https://www.youtube.com/embed/zrZPWK5Luws?feature=player_detailpage"]

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
 
    base_title = "NY Custom Hydroponics"
    if @title.nil?
      base_title
    else
      " | #{@title} | #{base_title} | "
    end
  end

  #def logo
  #  image_tag("logo.png", :alt => "sample app", :class => "round")
  #end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Videos", videos_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", contact_path %></li>
    </ul>

  </nav>
</footer>


app/views/layouts/_header.html.erb
      <header>
      <!-- <%# link_to logo, root_path #%> -->
        <nav class="round">
          <ul class="nav pull-right">
            <li><%= link_to "Home",    root_path %></li>
            <li><%= link_to "Help",    help_path %></li>
            <li><%= link_to "About",    about_path %></li>
            <li><%= link_to "Contact",   contact_path %></li>
            <li><%= link_to "Videos",    videos_path %></li>
          </ul>
        </nav>
      </header>


app/views/layouts/_javascripts.html.erb
    <%= javascript_include_tag :defaults %>
    

app/views/layouts/_stylesheets.html.erb

    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <!--[if lt IE 8]> <%= stylesheet_link_tag 'blueprint/ie' %> <![endif]-->

    <%= stylesheet_link_tag 'custom', :media => 'screen' %>


app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title> <%= title %> </title>
    <%= csrf_meta_tag %> 
    <%= render 'layouts/stylesheets' %>
    <%= render 'layouts/javascripts' %>
 </head>
  <body>
    <div class="container">
    <%= render 'layouts/header' %>

      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html> 

app/views/pages/about.html.erb
<h1>About Us</h1>
<h3>NY Custom Hydroponics</h3>
<p>
Moti Lebovich
</p>

app/views/pages/contact.html.erb
<h1>Contact </h1>

<p>
Moti Lebovich
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
for help withthis website 
urimikhli@gmail.com
</p>

app/views/pages/home.html.erb
<h1>NY Custom Hydroponics</h1>

<p>a little somethiing about us
and what we do
</p>

<div>
  latest video
  <%= render 'shared/video_embed_partial', { :video_src =>  @vid_src_array.last} %>
 <!-- <div id='lates_video'>
    <video width="320" height="240" controls>
      <source src="movie.mp4" type="video/mp4">
      <source src="movie.ogg" type="video/ogg">
      Your browser does not support the video tag.
    </video>
    
  </div>
-->
  <p></p>
  <%= link_to "Videos", 'videos' %>
  </div>

app/views/pages/videos.html.erb
<h1><%= @title %></h1>

<% i=0 %>
<% @vid_src_array.each do | video_src| %>
  <div>
    <% video_title = @vid_title_array[i] %>
    <%= "#{video_title}" %>
    <%= render 'shared/video_embed_partial', { :video_src => video_src} %>
  </div>
  <% i += 1 %>
<% end %>

app/views/shared/_video_embed_partial.html.erb
<!-- video embed partial-->

<iframe width="640" height="360" src=<%= video_src %> frameborder="0" allowfullscreen></iframe>